### ISSUE TITLE
[RFC] Overrides

### ISSUE THREAD

**Issue by notDavid** [dngray/ghacks-thunderbird-user.js#58]
Hi there,

what is currently the status of using something like `user-overrides.js` like how [Arkenffox](https://github.com/arkenfox/user.js/wiki/3.1-Overrides) does it?

Would it be a good idea to add this to your Wiki ?
(i couldn't find any info about it.)

Thank you!

**Comment by HorlogeSkynet** [comment]
Hello, everything is set to be used exactly like Arkenfox once #55 is merged. It adds support for latest ESR but as I don't have any platform to test it, so I'm waiting for a review from someone else (BTW this project requires another regular maintainer 🙃).

Thanks to you ! Bye 👋
